### ISSUE TITLE
长度为0 json格式化失败(疑似Cookie失效)

### ISSUE THREAD

**Issue by mxm-j** [Clov614/Microsoft_Rewards_Helper#1]
试了好几个请求的url的cookie都不行，请问是要用哪个请求？

Giftbox.json
food.json
Family_Tile.json
error?partial=true&X-Requested-With=XMLHttpRequest&_=1678363677840
collect
collect
clarity.js
Camera.json
book.json
bat.js
aria-webjs-sdk-a54a34c25f.js
animation-fc51cb13c9.js
angularcommonmodule-5e55ec3c35.js
angular-1b915e815a.js
amc.css
?qsp=true&content-type=application%2Fbond-compact-…53&time-delta-to-apply-millis=use-collector-delta
76hfh21kdi
137015850.js
137015850
0?ti=137015850&Ver=2&mid=f062c789-6033-4ac2-a7dd-8…ing.com%2F&r=&lt=1658&evt=pageLoad&sv=1&rn=593647
000400000383_262x164.png
%7B%7Bitem.imageUrl%7D%7D

**Comment by Clov614** [comment]
微软奖励的url或者bing.com的cookie
https://rewards.bing.com/

**Comment by Clov614** [comment]
注意在登录的时候需要勾选持久化登录，推测它的cookie值中的muid是必要的
![屏幕截图 2023-03-10 164535](https://user-images.githubusercontent.com/61135990/224268694-51fac481-7816-4d1a-84a1-7846ed8886ef.png)
![屏幕截图 2023-03-10 171307](https://user-images.githubusercontent.com/61135990/224275060-7f16af57-c2c5-4995-928e-2284b744bcbd.png)

**Comment by Clov614** [comment]
我知道了！也许是新账户，不存在手机分数，粗暴的错误处理导致了程序无法正常执行，感谢你的issue
