### ISSUE TITLE
建议增加运行完毕自动关闭该程序

### ISSUE THREAD

**Issue by wangmeng23** [Clov614/Microsoft_Rewards_Helper#2]
![image](https://user-images.githubusercontent.com/84214932/224474874-bfed831b-361f-4a95-b55d-a90b63c7c3ca.png)
我使用的是start cmd /C C:\Users\Administrator\Desktop\K\MicroSoftRewordsHelper.exe 无法自动关闭只能手动

**Comment by Clov614** [comment]
😄故意设置了阻塞，自动关闭就看不见交互信息了，目前在开发action版本，用GitHub的action自动化执行，弄个定时任务，内田自动执行，也就不需要每次本地执行了 👍

**Comment by Clov614** [comment]
用action版吧，不需要手动在本地运行
https://github.com/Clov614/microsoft-rewards-helper-action

**Comment by wangmeng23** [comment]
可以的
